server:
  port: 9000

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5430/test_db
    username: postgres
    password: postgres

  flyway:
    locations: classpath:/db/migration

jwt:
  password:
    encoder:
      secret: FZK2DZ82odqS13e8aENggaMbb_fAkl-nJL4AEVBX43g
      iteration: 64
      keylength: 256

  secret: b5f59337a612a2a7dc07328f3e7d1a04722967c7f06df20a499a7d3f91ff2a7e
  expiration: 86400
  refresh-expiration: 604800
  issuer: cit-sk.ru

logging:
  level:
    org.springframework.r2dbc: DEBUG
